#!/usr/bin/env python

###
# BCC unit cell with Periodic mesh in SALOME
author = "Sina Taghizadeh"
license = "GNU GPL Version 3.0"
###

import sys
import salome

salome.salome_init()
import salome_notebook
notebook = salome_notebook.NoteBook()
sys.path.insert(0, r'/home/Sina/Desktop/WorkDir/FinalData')    # The path must be changed based on current working dir (also in line 317)

###
### GEOM component
###

import GEOM
from salome.geom import geomBuilder
import math
import SALOMEDS


geompy = geomBuilder.New()
#Length of cube
a=5.0
#Radios of strut
r=0.9
#LengthDiscretization
Lw=r/2
#To make inside meshes bigger
n=2
#Name of file
name='1T02R16M36Nu'

O = geompy.MakeVertex(0, 0, 0)
OX = geompy.MakeVectorDXDYDZ(1, 0, 0)
OY = geompy.MakeVectorDXDYDZ(0, 1, 0)
OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)
Vertex_1 = geompy.MakeVertex(0, 0, 0)
Vertex_2 = geompy.MakeVertex(a, a, a)
Vertex_3 = geompy.MakeVertex(a, 0, 0)
Vertex_4 = geompy.MakeVertex(0, a, a)
Line_1 = geompy.MakeLineTwoPnt(Vertex_1, Vertex_2)
Line_2 = geompy.MakeLineTwoPnt(Vertex_3, Vertex_4)
Cylinder_1 = geompy.MakeCylinder(Vertex_1, Line_1, r, a)
Cylinder_2 = geompy.MakeCylinder(Vertex_3, Line_2, r, a)
Box_1 = geompy.MakeBoxDXDYDZ(a, a, a)
geompy.Rotate(Cylinder_1, Line_1, -150*math.pi/180.0)
geompy.Rotate(Cylinder_2, Line_2, -30*math.pi/180.0)
Fuse_1 = geompy.MakeFuseList([Cylinder_1, Cylinder_2], True, True)
geompy.TranslateDXDYDZ(Box_1, -a/2, -a/2, -a/2)
geompy.TranslateDXDYDZ(Fuse_1, -a/2, -a/2, -a/2)
Plane_1 = geompy.MakePlane(O, OY, 2*a)
Plane_2 = geompy.MakePlane(O, OZ, 2*a)
Translation_1 = geompy.MakeTranslation(Box_1, 0, a/2, 0)
Cut_1 = geompy.MakeCutList(Fuse_1, [Translation_1], True)
Translation_2 = geompy.MakeTranslation(Box_1, 0, 0, a/2)
Cut_2 = geompy.MakeCutList(Cut_1, [Translation_2], True)
Mirror_1 = geompy.MakeMirrorByPlane(Cut_2, Plane_1)
Fuse_2 = geompy.MakeFuseList([Cut_2, Mirror_1], True, True)
Mirror_2 = geompy.MakeMirrorByPlane(Fuse_2, Plane_2)
Fuse_3 = geompy.MakeFuseList([Fuse_2, Mirror_2], True, True)
mat = geompy.MakeCutList(Box_1, [Fuse_3], True)
inc = geompy.MakeCommonList([Box_1, Fuse_3], True)
composite = geompy.MakePartition([mat, inc], [], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
mat_1 = geompy.CreateGroup(composite, geompy.ShapeType["SOLID"])
geompy.UnionIDs(mat_1, [2])
inc_1 = geompy.CreateGroup(composite, geompy.ShapeType["SOLID"])
geompy.UnionIDs(inc_1, [126])
edges = geompy.CreateGroup(composite, geompy.ShapeType["EDGE"])
geompy.UnionIDs(edges, [6, 9, 11, 13, 15, 17, 19, 21, 24, 27, 29, 31, 33, 35, 36, 39, 41, 42, 43, 44, 45, 46, 47, 48, 51, 53, 55, 57, 59, 62, 63, 64, 65, 66, 67, 68, 71, 74, 76, 78, 79, 82, 83, 84, 85, 86, 89, 91, 93, 94, 97, 98, 101, 102, 103, 104, 105, 106, 107, 110, 111, 112, 115, 116, 119, 121, 122, 125, 130, 132, 135, 140, 142, 145, 150, 152, 155, 160, 162, 165, 170, 172, 175, 180, 182, 185, 190, 192, 195, 200, 202, 205])
Group_1 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_1, [108])
Group_2 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_2, [49])
Group_3 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_3, [22])
Group_4 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_4, [4])
Group_5 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_5, [87])
Group_6 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_6, [69])
Group_7 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_7, [176])
Group_8 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_8, [206])
Group_9 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_9, [156])
Group_10 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_10, [196])
Group_11 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_11, [173])
Group_12 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_12, [203])
Group_13 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_13, [143])
Group_14 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_14, [183])
Group_15 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_15, [146])
Group_16 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_16, [168])
Group_17 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_17, [148])
Group_18 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_18, [133])
Group_19 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_19, [178])
Group_20 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_20, [138])
Group_21 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_21, [158])
Group_22 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_22, [128])
Group_23 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_23, [163])
Group_24 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_24, [136])
Group_25 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_25, [193])
Group_26 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_26, [153])
Group_27 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_27, [198])
Group_28 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_28, [186])
Group_29 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_29, [188])
Group_30 = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(Group_30, [166])
BCCshell = geompy.CreateGroup(composite, geompy.ShapeType["FACE"])
geompy.UnionIDs(BCCshell, [117, 80, 95, 99, 113, 60, 37, 123])
[mat_1, inc_1, edges, Group_1, Group_2, Group_3, Group_4, Group_5, Group_6, Group_7, Group_8, Group_9, Group_10, Group_11, Group_12, Group_13, Group_14, Group_15, Group_16, Group_17, Group_18, Group_19, Group_20, Group_21, Group_22, Group_23, Group_24, Group_25, Group_26, Group_27, Group_28, Group_29, Group_30, BCCshell] = geompy.GetExistingSubObjects(composite, False)
geompy.addToStudy( O, 'O' )
geompy.addToStudy( OX, 'OX' )
geompy.addToStudy( OY, 'OY' )
geompy.addToStudy( OZ, 'OZ' )
geompy.addToStudy( Vertex_1, 'Vertex_1' )
geompy.addToStudy( Vertex_2, 'Vertex_2' )
geompy.addToStudy( Vertex_3, 'Vertex_3' )
geompy.addToStudy( Vertex_4, 'Vertex_4' )
geompy.addToStudy( Line_1, 'Line_1' )
geompy.addToStudy( Line_2, 'Line_2' )
geompy.addToStudy( Cylinder_1, 'Cylinder_1' )
geompy.addToStudy( Cylinder_2, 'Cylinder_2' )
geompy.addToStudy( Box_1, 'Box_1' )
geompy.addToStudy( Fuse_1, 'Fuse_1' )
geompy.addToStudy( Plane_1, 'Plane_1' )
geompy.addToStudy( Plane_2, 'Plane_2' )
geompy.addToStudy( Translation_1, 'Translation_1' )
geompy.addToStudy( Cut_1, 'Cut_1' )
geompy.addToStudy( Translation_2, 'Translation_2' )
geompy.addToStudy( Cut_2, 'Cut_2' )
geompy.addToStudy( Mirror_1, 'Mirror_1' )
geompy.addToStudy( Fuse_2, 'Fuse_2' )
geompy.addToStudy( Mirror_2, 'Mirror_2' )
geompy.addToStudy( Fuse_3, 'Fuse_3' )
geompy.addToStudy( mat, 'mat' )
geompy.addToStudy( inc, 'inc' )
geompy.addToStudy( composite, 'composite' )
geompy.addToStudyInFather( composite, mat_1, 'mat' )
geompy.addToStudyInFather( composite, inc_1, 'inc' )
geompy.addToStudyInFather( composite, edges, 'edges' )
geompy.addToStudyInFather( composite, Group_1, 'Group_1' )
geompy.addToStudyInFather( composite, Group_2, 'Group_2' )
geompy.addToStudyInFather( composite, Group_3, 'Group_3' )
geompy.addToStudyInFather( composite, Group_4, 'Group_4' )
geompy.addToStudyInFather( composite, Group_5, 'Group_5' )
geompy.addToStudyInFather( composite, Group_6, 'Group_6' )
geompy.addToStudyInFather( composite, Group_7, 'Group_7' )
geompy.addToStudyInFather( composite, Group_8, 'Group_8' )
geompy.addToStudyInFather( composite, Group_9, 'Group_9' )
geompy.addToStudyInFather( composite, Group_10, 'Group_10' )
geompy.addToStudyInFather( composite, Group_11, 'Group_11' )
geompy.addToStudyInFather( composite, Group_12, 'Group_12' )
geompy.addToStudyInFather( composite, Group_13, 'Group_13' )
geompy.addToStudyInFather( composite, Group_14, 'Group_14' )
geompy.addToStudyInFather( composite, Group_15, 'Group_15' )
geompy.addToStudyInFather( composite, Group_16, 'Group_16' )
geompy.addToStudyInFather( composite, Group_17, 'Group_17' )
geompy.addToStudyInFather( composite, Group_18, 'Group_18' )
geompy.addToStudyInFather( composite, Group_19, 'Group_19' )
geompy.addToStudyInFather( composite, Group_20, 'Group_20' )
geompy.addToStudyInFather( composite, Group_21, 'Group_21' )
geompy.addToStudyInFather( composite, Group_22, 'Group_22' )
geompy.addToStudyInFather( composite, Group_23, 'Group_23' )
geompy.addToStudyInFather( composite, Group_24, 'Group_24' )
geompy.addToStudyInFather( composite, Group_25, 'Group_25' )
geompy.addToStudyInFather( composite, Group_26, 'Group_26' )
geompy.addToStudyInFather( composite, Group_27, 'Group_27' )
geompy.addToStudyInFather( composite, Group_28, 'Group_28' )
geompy.addToStudyInFather( composite, Group_29, 'Group_29' )
geompy.addToStudyInFather( composite, Group_30, 'Group_30' )
geompy.addToStudyInFather( composite, BCCshell, 'BCCshell' )

###
### SMESH component
###

import  SMESH, SALOMEDS
from salome.smesh import smeshBuilder

smesh = smeshBuilder.New()
#smesh.SetEnablePublish( False ) # Set to False to avoid publish in study if not needed or in some particular situations:
                                 # multiples meshes built in parallel, complex and numerous mesh edition (performance)

Mesh_1 = smesh.Mesh(composite,'Mesh_1')
NETGEN_3D = Mesh_1.Tetrahedron()
Max_Element_Volume_1 = NETGEN_3D.MaxElementVolume(1000)
mat_2 = Mesh_1.GroupOnGeom(mat_1,'mat',SMESH.VOLUME)
inc_2 = Mesh_1.GroupOnGeom(inc_1,'inc',SMESH.VOLUME)
edges_1 = Mesh_1.GroupOnGeom(edges,'edges',SMESH.EDGE)
Group_1_1 = Mesh_1.GroupOnGeom(Group_1,'Group_1',SMESH.FACE)
Group_2_1 = Mesh_1.GroupOnGeom(Group_2,'Group_2',SMESH.FACE)
Group_3_1 = Mesh_1.GroupOnGeom(Group_3,'Group_3',SMESH.FACE)
Group_4_1 = Mesh_1.GroupOnGeom(Group_4,'Group_4',SMESH.FACE)
Group_5_1 = Mesh_1.GroupOnGeom(Group_5,'Group_5',SMESH.FACE)
Group_6_1 = Mesh_1.GroupOnGeom(Group_6,'Group_6',SMESH.FACE)
Group_7_1 = Mesh_1.GroupOnGeom(Group_7,'Group_7',SMESH.FACE)
Group_8_1 = Mesh_1.GroupOnGeom(Group_8,'Group_8',SMESH.FACE)
Group_9_1 = Mesh_1.GroupOnGeom(Group_9,'Group_9',SMESH.FACE)
Group_10_1 = Mesh_1.GroupOnGeom(Group_10,'Group_10',SMESH.FACE)
Group_11_1 = Mesh_1.GroupOnGeom(Group_11,'Group_11',SMESH.FACE)
Group_12_1 = Mesh_1.GroupOnGeom(Group_12,'Group_12',SMESH.FACE)
Group_13_1 = Mesh_1.GroupOnGeom(Group_13,'Group_13',SMESH.FACE)
Group_14_1 = Mesh_1.GroupOnGeom(Group_14,'Group_14',SMESH.FACE)
Group_15_1 = Mesh_1.GroupOnGeom(Group_15,'Group_15',SMESH.FACE)
Group_16_1 = Mesh_1.GroupOnGeom(Group_16,'Group_16',SMESH.FACE)
Group_17_1 = Mesh_1.GroupOnGeom(Group_17,'Group_17',SMESH.FACE)
Group_18_1 = Mesh_1.GroupOnGeom(Group_18,'Group_18',SMESH.FACE)
Group_19_1 = Mesh_1.GroupOnGeom(Group_19,'Group_19',SMESH.FACE)
Group_20_1 = Mesh_1.GroupOnGeom(Group_20,'Group_20',SMESH.FACE)
Group_21_1 = Mesh_1.GroupOnGeom(Group_21,'Group_21',SMESH.FACE)
Group_22_1 = Mesh_1.GroupOnGeom(Group_22,'Group_22',SMESH.FACE)
Group_23_1 = Mesh_1.GroupOnGeom(Group_23,'Group_23',SMESH.FACE)
Group_24_1 = Mesh_1.GroupOnGeom(Group_24,'Group_24',SMESH.FACE)
Group_25_1 = Mesh_1.GroupOnGeom(Group_25,'Group_25',SMESH.FACE)
Group_26_1 = Mesh_1.GroupOnGeom(Group_26,'Group_26',SMESH.FACE)
Group_27_1 = Mesh_1.GroupOnGeom(Group_27,'Group_27',SMESH.FACE)
Group_28_1 = Mesh_1.GroupOnGeom(Group_28,'Group_28',SMESH.FACE)
Group_29_1 = Mesh_1.GroupOnGeom(Group_29,'Group_29',SMESH.FACE)
Group_30_1 = Mesh_1.GroupOnGeom(Group_30,'Group_30',SMESH.FACE)
BCCshell_1 = Mesh_1.GroupOnGeom(BCCshell,'BCCshell',SMESH.FACE)
Regular_1D = Mesh_1.Segment(geom=edges)
Local_Length_1 = Regular_1D.LocalLength(Lw,None,1e-07)
NETGEN_2D = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=BCCshell)
Max_Element_Area_1 = NETGEN_2D.MaxElementArea(n*Lw**2)
NETGEN_2D_1 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_1)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_1)
NETGEN_2D_2 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_2)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_2)
NETGEN_2D_3 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_3)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_3)
NETGEN_2D_4 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_7)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_7)
NETGEN_2D_5 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_8)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_8)
NETGEN_2D_6 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_9)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_9)
NETGEN_2D_7 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_10)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_10)
NETGEN_2D_8 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_11)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_11)
NETGEN_2D_9 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_12)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_12)
NETGEN_2D_10 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_13)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_13)
NETGEN_2D_11 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_14)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_14)
NETGEN_2D_12 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_15)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_15)
NETGEN_2D_13 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_16)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_16)
NETGEN_2D_14 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_17)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_17)
NETGEN_2D_15 = Mesh_1.Triangle(algo=smeshBuilder.NETGEN_2D,geom=Group_18)
status = Mesh_1.AddHypothesis(Max_Element_Area_1,Group_18)
Projection_2D = Mesh_1.Projection2D(geom=Group_4)
Source_Face_1 = Projection_2D.SourceFace(Group_1,None,None,None,None,None)
Projection_2D_1 = Mesh_1.Projection2D(geom=Group_5)
Source_Face_2 = Projection_2D_1.SourceFace(Group_2,None,None,None,None,None)
Projection_2D_2 = Mesh_1.Projection2D(geom=Group_6)
Source_Face_3 = Projection_2D_2.SourceFace(Group_3,None,None,None,None,None)
Projection_2D_3 = Mesh_1.Projection2D(geom=Group_19)
Source_Face_4 = Projection_2D_3.SourceFace(Group_8,None,None,None,None,None)
Projection_2D_4 = Mesh_1.Projection2D(geom=Group_20)
Source_Face_5 = Projection_2D_4.SourceFace(Group_7,None,None,None,None,None)
Projection_2D_5 = Mesh_1.Projection2D(geom=Group_21)
Source_Face_6 = Projection_2D_5.SourceFace(Group_10,None,None,None,None,None)
Projection_2D_6 = Mesh_1.Projection2D(geom=Group_22)
Source_Face_7 = Projection_2D_6.SourceFace(Group_9,None,None,None,None,None)
Projection_2D_7 = Mesh_1.Projection2D(geom=Group_23)
Source_Face_8 = Projection_2D_7.SourceFace(Group_14,None,None,None,None,None)
Projection_2D_8 = Mesh_1.Projection2D(geom=Group_24)
Source_Face_9 = Projection_2D_8.SourceFace(Group_13,None,None,None,None,None)
Projection_2D_9 = Mesh_1.Projection2D(geom=Group_25)
Source_Face_10 = Projection_2D_9.SourceFace(Group_12,None,None,None,None,None)
Projection_2D_10 = Mesh_1.Projection2D(geom=Group_26)
Source_Face_11 = Projection_2D_10.SourceFace(Group_11,None,None,None,None,None)
Projection_2D_11 = Mesh_1.Projection2D(geom=Group_27)
Source_Face_12 = Projection_2D_11.SourceFace(Group_16,None,None,None,None,None)
Projection_2D_12 = Mesh_1.Projection2D(geom=Group_28)
Source_Face_13 = Projection_2D_12.SourceFace(Group_15,None,None,None,None,None)
Projection_2D_13 = Mesh_1.Projection2D(geom=Group_29)
Source_Face_14 = Projection_2D_13.SourceFace(Group_17,None,None,None,None,None)
Projection_2D_14 = Mesh_1.Projection2D(geom=Group_30)
Source_Face_15 = Projection_2D_14.SourceFace(Group_18,None,None,None,None,None)
isDone = Mesh_1.Compute()
[ mat_2, inc_2, edges_1, Group_1_1, Group_2_1, Group_3_1, Group_4_1, Group_5_1, Group_6_1, Group_7_1, Group_8_1, Group_9_1, Group_10_1, Group_11_1, Group_12_1, Group_13_1, Group_14_1, Group_15_1, Group_16_1, Group_17_1, Group_18_1, Group_19_1, Group_20_1, Group_21_1, Group_22_1, Group_23_1, Group_24_1, Group_25_1, Group_26_1, Group_27_1, Group_28_1, Group_29_1, Group_30_1, BCCshell_1 ] = Mesh_1.GetGroups()
smesh.SetName(Mesh_1, 'Mesh_1')
try:
  Mesh_1.ExportMED( r'/home/Sina/Desktop/WorkDir/FinalData/'+name+'.med', 0, 41, 1, Mesh_1, 1, [], '',-1, 1 ) #The path must be changed based on current working dir (like line 15)
  pass
except:
  print('ExportPartToMED() failed. Invalid file name?')
Sub_mesh_1 = Regular_1D.GetSubMesh()
Sub_mesh_2 = NETGEN_2D.GetSubMesh()
Sub_mesh_3 = NETGEN_2D_1.GetSubMesh()
Sub_mesh_4 = NETGEN_2D_2.GetSubMesh()
Sub_mesh_5 = NETGEN_2D_3.GetSubMesh()
Sub_mesh_6 = NETGEN_2D_4.GetSubMesh()
Sub_mesh_7 = NETGEN_2D_5.GetSubMesh()
Sub_mesh_8 = NETGEN_2D_6.GetSubMesh()
Sub_mesh_9 = NETGEN_2D_7.GetSubMesh()
Sub_mesh_10 = NETGEN_2D_8.GetSubMesh()
Sub_mesh_11 = NETGEN_2D_9.GetSubMesh()
Sub_mesh_12 = NETGEN_2D_10.GetSubMesh()
Sub_mesh_13 = NETGEN_2D_11.GetSubMesh()
Sub_mesh_14 = NETGEN_2D_12.GetSubMesh()
Sub_mesh_15 = NETGEN_2D_13.GetSubMesh()
Sub_mesh_16 = NETGEN_2D_14.GetSubMesh()
Sub_mesh_17 = NETGEN_2D_15.GetSubMesh()
Sub_mesh_18 = Projection_2D.GetSubMesh()
Sub_mesh_19 = Projection_2D_1.GetSubMesh()
Sub_mesh_20 = Projection_2D_2.GetSubMesh()
Sub_mesh_21 = Projection_2D_3.GetSubMesh()
Sub_mesh_22 = Projection_2D_4.GetSubMesh()
Sub_mesh_23 = Projection_2D_5.GetSubMesh()
Sub_mesh_24 = Projection_2D_6.GetSubMesh()
Sub_mesh_25 = Projection_2D_7.GetSubMesh()
Sub_mesh_26 = Projection_2D_8.GetSubMesh()
Sub_mesh_27 = Projection_2D_9.GetSubMesh()
Sub_mesh_28 = Projection_2D_10.GetSubMesh()
Sub_mesh_29 = Projection_2D_11.GetSubMesh()
Sub_mesh_30 = Projection_2D_12.GetSubMesh()
Sub_mesh_31 = Projection_2D_13.GetSubMesh()
Sub_mesh_32 = Projection_2D_14.GetSubMesh()


## Set names of Mesh objects
smesh.SetName(Sub_mesh_31, 'Sub-mesh_31')
smesh.SetName(Sub_mesh_30, 'Sub-mesh_30')
smesh.SetName(Sub_mesh_29, 'Sub-mesh_29')
smesh.SetName(Sub_mesh_28, 'Sub-mesh_28')
smesh.SetName(Sub_mesh_27, 'Sub-mesh_27')
smesh.SetName(Sub_mesh_26, 'Sub-mesh_26')
smesh.SetName(Sub_mesh_25, 'Sub-mesh_25')
smesh.SetName(Sub_mesh_24, 'Sub-mesh_24')
smesh.SetName(Sub_mesh_23, 'Sub-mesh_23')
smesh.SetName(Sub_mesh_22, 'Sub-mesh_22')
smesh.SetName(Sub_mesh_2, 'Sub-mesh_2')
smesh.SetName(Sub_mesh_1, 'Sub-mesh_1')
smesh.SetName(edges_1, 'edges')
smesh.SetName(Source_Face_10, 'Source Face_10')
smesh.SetName(Source_Face_9, 'Source Face_9')
smesh.SetName(Source_Face_8, 'Source Face_8')
smesh.SetName(Source_Face_7, 'Source Face_7')
smesh.SetName(Source_Face_14, 'Source Face_14')
smesh.SetName(Source_Face_13, 'Source Face_13')
smesh.SetName(Source_Face_12, 'Source Face_12')
smesh.SetName(Source_Face_11, 'Source Face_11')
smesh.SetName(Source_Face_15, 'Source Face_15')
smesh.SetName(inc_2, 'inc')
smesh.SetName(mat_2, 'mat')
smesh.SetName(Sub_mesh_11, 'Sub-mesh_11')
smesh.SetName(Sub_mesh_10, 'Sub-mesh_10')
smesh.SetName(Sub_mesh_7, 'Sub-mesh_7')
smesh.SetName(Sub_mesh_6, 'Sub-mesh_6')
smesh.SetName(Sub_mesh_9, 'Sub-mesh_9')
smesh.SetName(Sub_mesh_8, 'Sub-mesh_8')
smesh.SetName(Sub_mesh_3, 'Sub-mesh_3')
smesh.SetName(Sub_mesh_5, 'Sub-mesh_5')
smesh.SetName(Sub_mesh_4, 'Sub-mesh_4')
smesh.SetName(Local_Length_1, 'Local Length_1')
smesh.SetName(Max_Element_Area_1, 'Max. Element Area_1')
smesh.SetName(Max_Element_Volume_1, 'Max. Element Volume_1')
smesh.SetName(Source_Face_3, 'Source Face_3')
smesh.SetName(Source_Face_4, 'Source Face_4')
smesh.SetName(Source_Face_1, 'Source Face_1')
smesh.SetName(Source_Face_2, 'Source Face_2')
smesh.SetName(Group_28_1, 'Group_28')
smesh.SetName(Group_29_1, 'Group_29')
smesh.SetName(Source_Face_5, 'Source Face_5')
smesh.SetName(Source_Face_6, 'Source Face_6')
smesh.SetName(Group_22_1, 'Group_22')
smesh.SetName(Group_23_1, 'Group_23')
smesh.SetName(Group_20_1, 'Group_20')
smesh.SetName(Group_21_1, 'Group_21')
smesh.SetName(Group_26_1, 'Group_26')
smesh.SetName(Group_27_1, 'Group_27')
smesh.SetName(Group_24_1, 'Group_24')
smesh.SetName(Group_25_1, 'Group_25')
smesh.SetName(Group_19_1, 'Group_19')
smesh.SetName(Group_18_1, 'Group_18')
smesh.SetName(Group_11_1, 'Group_11')
smesh.SetName(Group_10_1, 'Group_10')
smesh.SetName(Group_13_1, 'Group_13')
smesh.SetName(Group_12_1, 'Group_12')
smesh.SetName(Group_15_1, 'Group_15')
smesh.SetName(Group_14_1, 'Group_14')
smesh.SetName(Group_17_1, 'Group_17')
smesh.SetName(Group_16_1, 'Group_16')
smesh.SetName(Mesh_1.GetMesh(), 'Mesh_1')
smesh.SetName(BCCshell_1, 'BCCshell')
smesh.SetName(Group_30_1, 'Group_30')
smesh.SetName(NETGEN_3D.GetAlgorithm(), 'NETGEN 3D')
smesh.SetName(NETGEN_2D.GetAlgorithm(), 'NETGEN 2D')
smesh.SetName(Regular_1D.GetAlgorithm(), 'Regular_1D')
smesh.SetName(Projection_2D.GetAlgorithm(), 'Projection_2D')
smesh.SetName(Sub_mesh_20, 'Sub-mesh_20')
smesh.SetName(Sub_mesh_21, 'Sub-mesh_21')
smesh.SetName(Sub_mesh_16, 'Sub-mesh_16')
smesh.SetName(Sub_mesh_17, 'Sub-mesh_17')
smesh.SetName(Sub_mesh_18, 'Sub-mesh_18')
smesh.SetName(Sub_mesh_19, 'Sub-mesh_19')
smesh.SetName(Sub_mesh_12, 'Sub-mesh_12')
smesh.SetName(Sub_mesh_13, 'Sub-mesh_13')
smesh.SetName(Sub_mesh_14, 'Sub-mesh_14')
smesh.SetName(Sub_mesh_15, 'Sub-mesh_15')
smesh.SetName(Sub_mesh_32, 'Sub-mesh_32')
smesh.SetName(Group_8_1, 'Group_8')
smesh.SetName(Group_9_1, 'Group_9')
smesh.SetName(Group_1_1, 'Group_1')
smesh.SetName(Group_2_1, 'Group_2')
smesh.SetName(Group_3_1, 'Group_3')
smesh.SetName(Group_4_1, 'Group_4')
smesh.SetName(Group_5_1, 'Group_5')
smesh.SetName(Group_6_1, 'Group_6')
smesh.SetName(Group_7_1, 'Group_7')


if salome.sg.hasDesktop():
  salome.sg.updateObjBrowser()
